# Generated by Django 3.2.7 on 2022-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
