# Generated by Django 3.2.7 on 2022-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0005_remove_userprofile_phone_numer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentoring',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_address',
            field=models.TextField(max_length=50),
        ),
    ]
