# Generated by Django 3.2.7 on 2022-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0006_auto_20220211_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.TextField(default=''),
        ),
    ]
