# Generated by Django 3.2.7 on 2022-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0007_auto_20220215_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year_group',
            field=models.TextField(default=''),
        ),
    ]
