# Generated by Django 3.2.7 on 2022-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0008_userprofile_year_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.TextField(default=''),
        ),
    ]
