# Generated by Django 3.2.7 on 2022-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0009_userprofile_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.ManyToManyField(to='FindMeA.Interest'),
        ),
    ]
