# Generated by Django 3.2.7 on 2022-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0010_auto_20220216_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.TextField(default=''),
        ),
    ]
