# Generated by Django 3.2.7 on 2022-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0011_auto_20220216_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mentor_subject',
            field=models.TextField(default='Not Applicable'),
        ),
    ]
