# Generated by Django 3.2.7 on 2022-02-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0012_userprofile_mentor_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mentor_subject',
            new_name='mentor_subjects',
        ),
    ]
