# Generated by Django 3.2.7 on 2022-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0015_remove_interest_mentor_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_text', models.CharField(default='Not Applicable', max_length=200)),
            ],
        ),
    ]
