# Generated by Django 3.2.7 on 2022-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0016_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_text',
            field=models.CharField(max_length=200),
        ),
    ]
