# Generated by Django 3.2.7 on 2022-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0017_alter_mentor_mentor_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mentor_subjects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_subjects',
            field=models.ManyToManyField(related_name='mentor_subjects', to='FindMeA.Interest'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_interests',
            field=models.ManyToManyField(related_name='user_interests', to='FindMeA.Interest'),
        ),
    ]
