# Generated by Django 3.2.7 on 2022-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0020_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recieved_date',
            new_name='sent_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='notes',
            field=models.TextField(default='', max_length=500),
        ),
    ]
