# Generated by Django 3.2.7 on 2022-04-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindMeA', '0021_auto_20220426_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_date',
        ),
    ]
